### ISSUE TITLE
[Training] Cuda OOM error with H100 (80G)

### ISSUE THREAD

**Issue by yjhong89** [aigc-apps/EasyAnimate#200]
Hi! Thanks for sharing great work!

While I am trying to fine-tune EasyAnimateV5.1-7b (I2V) with my custom dataset, CUDA OOM error occured even with 4 80g GPUs.

Here is my training script
- Set 512x512x49
- set low_vram option

```
export MODEL_NAME="/data/video_generation/EasyAnimateV5.1/EasyAnimateV5.1-7b-zh-InP"
export DATASET_NAME="/data/VFHQ/processed_hunyuan"
export DATASET_META_NAME="/data/VFHQ/video2caption_re_.json"
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
export CUDA_VISIBLE_DEVICES=4,5,6,7
NCCL_DEBUG=INFO

# When train model with multi machines, use "--config_file accelerate.yaml" instead of "--mixed_precision='bf16'".
accelerate launch --mixed_precision="bf16" scripts/train.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$DATASET_NAME \
  --train_data_meta=$DATASET_META_NAME \
  --config_path "config/easyanimate_video_v5.1_magvit_qwen.yaml" \
  --image_sample_size=512 \
  --video_sample_size=512 \
  --token_sample_size=512 \
  --video_sample_stride=3 \
  --video_sample_n_frames=49 \
  --train_batch_size=1 \
  --video_repeat=1 \
  --gradient_accumulation_steps=1 \
  --dataloader_num_workers=8 \
  --num_train_epochs=100 \
  --checkpointing_steps=100 \
  --learning_rate=2e-05 \
  --lr_scheduler="constant_with_warmup" \
  --lr_warmup_steps=100 \
  --seed=42 \
  --output_dir="/users/yjhong/diffusion_i2v/EasyAnimateV5.1" \
  --gradient_checkpointing \
  --mixed_precision="bf16" \
  --adam_weight_decay=5e-2 \
  --adam_epsilon=1e-10 \
  --vae_mini_batch=1 \
  --max_grad_norm=0.05 \
  --random_hw_adapt \
  --training_with_video_token_length \
  --loss_type="flow" \
  --enable_bucket \
  --uniform_sampling \
  --low_vram \
  --train_mode="inpaint" \
  --trainable_modules "."
```

- Error raised after 1 step

![Image](https://github.com/user-attachments/assets/90b92b42-de14-4ee3-940e-5e80a004d049)

### Questions
- Is there any way to fine-tune ? (pre-loading vae and text latents or modify something)
- Is it possible to use deepspeed for single-node and multi-gpu ??

**Comment by hkunzhe** [comment]
@yjhong89, To reduce the GPU memory, you can try to use DeepSpeed ZeRO-2 as https://github.com/aigc-apps/EasyAnimate/blob/main/scripts/train_reward_lora.sh#L11 .

**Comment by yjhong89** [comment]
Thanks! it works!
